apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: rollout-health-check
  namespace: demo
spec:
  metrics:
  - name: tcp-check
    interval: 15s
    count: 3
    successCondition: result == 200
    failureCondition: result != 200
    provider:
      web:
        url: http://rollout-demo-canary.demo.svc.cluster.local:5000/
        method: GET
        timeoutSeconds: 5
