apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-demo
  labels:
    app: python-demo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-demo 
  template:
    metadata:
      labels:
        app: python-demo 
    spec:
      containers:
      - name: python-demo
        image: justinmihigo/python-demo:7
        ports:
        - containerPort: 5000
