apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rollout-demo-route
  namespace: demo
  annotations:
    konghq.com/strip-path: "true"
  labels:
    app: rollout-demo
spec:
  parentRefs:
  - name: kong
    namespace: kong    
  hostnames:
  - rollout-demo.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: rollout-demo-stable
      port: 80
      weight: 100
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
      - type: ExtensionRef
        extensionRef:
          group: configuration.konghq.com
          kind: KongPlugin
          name: ip-whitelist
    backendRefs:    
    - name: rollout-demo-canary
      port: 80
      weight: 0
