name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'manifest/*.yaml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'manifest/*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-demo .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-demo
